function blank(){return"<html></html>"}function UpdateFavoriteMessage(a,d,b,c,e,f,g){XmlHttpMethod(d,ToggleFavoriteMessageIcon(a,b,c),!1);(a=top)&&a.UpdateFolderCount(e,f);(e=window.frames.mainmenu)&&g&&e.location.reload()}
function ToggleFavoriteMessageIcon(a,d,b){a=a.childNodes[0];0<=a.src.indexOf("favorite_on16.png")?(a.src=a.src.replace("favorite_on16.png","favorite_off16.png"),a.title=d):0<=a.src.indexOf("favorite_on24.png")?(a.src=a.src.replace("favorite_on24.png","favorite_off24.png"),a.title=d):0<=a.src.indexOf("favorite_off16.png")?(a.src=a.src.replace("favorite_off16.png","favorite_on16.png"),a.title=b):0<=a.src.indexOf("favorite_off24.png")&&(a.src=a.src.replace("favorite_off24.png","favorite_on24.png"),a.title=
b)}function OnKeyPress(a){}function ConfirmCancel(a,d){if(!confirm(a))return!1;null!=d&&location.replace(d);return!0}function ReloadLogin(a,d,b,c,e,f,g){a+="?"+d+"="+document.getElementById(b).value;a+="&"+c+"="+document.getElementById(e).value;a+="&"+f+"="+document.getElementById(g).value;location.replace(a)}
function ToggleInfoBox(a,d,b,c){var e=document.getElementById(a);null!=e&&(a="h-hidden"==e.className,e.className=a?"":"h-hidden",null!=b&&null!=c&&(d=document.getElementById(d),null!=d&&(d.innerHTML=a?c:b)))}var _POPUP_FEATURES="location=0,statusbar=0,menubar=0,width=400,height=300";function raw_popup(a,d,b){if(null==b||""==b)b=_POPUP_FEATURES;if(null==d||""==d)d="_blank";a=window.open(a,d,b);a.focus();return a}
function OpenPopup(a,d,b){if(null==b||""==b)b=a.getAttribute("href");return raw_popup(b,a.getAttribute("target")||"_blank",d)}function IsValidExtension(a,d){for(var b=GetFileExtension(a),c=d.split(","),e=0;e<c.length;e++)if(s=c[e],0<=s.indexOf(b))return!0;return!1}function GetFileExtension(a){var d=a.lastIndexOf(".");return a.substring(d+1,a.length)}
function GetChat(a,d,b){var c;c='<OBJECT classid="clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" width="725" height="403" align="baseline" codebase="http://java.sun.com/products/plugin/1.3/jinstall-13-win32.cab#Version=1,3,0,0"><PARAM NAME="type" VALUE="application/x-java-applet;version=1.3"><PARAM NAME="scriptable" VALUE="false">';c+='<param name="Archive" value="XChat2.jar">';c+='<param name="CODE" value="XChat2.XChat2.class">';c+='<param name="Nickname" value="'+a+'">';c+='<param name="Channel" value="#Lobby">';
c+='<param name="Server" value="'+d+'">';c+='<param name="Codebase" value="http://'+d+'/chat/" >';c+='<param name="Port" value="'+b+'">';c+='<param name="Password" value="">';c+='<param name="Password" value="PASS">';c+='<param name="ColorRGB" value="247,146,74">';c+="<COMMENT>";c+="<EMBED ";c+='type="application/x-java-applet;version=1.3"';c+='WIDTH = "725" ';c+='HEIGHT = "403" ';c+='ALIGN = "baseline" ';c+='java_Archive = "XChat2.jar" ';c+='java_CODE = "XChat2.XChat2.class" ';c+='java_CODEBASE = "http://'+
d+'/chat/"';c+='Nickname = "'+a+'" ';c+='Channel = "#Lobby" ';c+='Server = "'+d+'"';c+='Port = "'+b+'" ';c+='Password = "" ';c+='Password = "PASS" ';c+='ColorRGB = "247,146,74" ';c+='scriptable=false pluginspage="http://java.sun.com/products/plugin/1.3/plugin-install.html">';c+="<NOEMBED></COMMENT>";c+="</NOEMBED></EMBED></OBJECT>";document.write(c)}
function GetConferenceNew(a,d,b,c,e,f,g,h,k,l,m,n,p,q,r,t,u,v,w){a='<object classid="clsid:8AD9C840-044E-11D1-B3E9-00805F499D93" codebase="http://java.sun.com/update/1.4.2/jinstall-1_4-windows-i586.cab#Version=1,4,0,0" width="'+d+'%" height="'+b+'%" id="Talx" name="Talx"><param name="code" value="Talx">';a+='<param name="archive" value="talx.jar">';a+='<param name="type" value="application/x-java-applet;version=1.4">';a+='<param name="RoomName" value="'+f+'">';a+='<param name="RoomPwd" value="'+g+
'">';a+='<param name="ServerPort" value="'+e+'">';a+='<param name="ServerIP" value="'+c+'">';a+='<param name="RealName" value="'+k+'">';a+='<param name="UserName" value="'+h+'">';a+='<param name="PersonalPictureURL" value="'+m+'">';a+='<param name="EnablePersonalPictureURL" value="'+l+'">';a+='<param name="PersonalPictureHeight" value="'+u+'">';a+='<param name="PersonalColor" value="'+n+'">';a+='<param name="Supervisor" value="'+p+'">';a+='<param name="EnableWritingBoard" value="'+q+'">';a+='<param name="EnableDrawingBoard" value="'+
r+'">';a+='<param name="CanEditWritingBoard" value="'+t+'">';a+='<param name="MaxWritingBoardPages" value="'+v+'">';a+='<param name="Signature" value="'+w+'">';a+="<comment>";a+='<applet pluginspage="http://java.sun.com/products/plugin/index.html#download" ';a+='id ="Talx2" ';a+='name ="Talx2" ';a+='width ="'+d+'%" ';a+='height ="'+b+'%" ';a+='code =" Talx" ';a+='archive =" talx.jar" ';a+='type =" application/x-java-applet;version=1.4" ';a+='RoomName ="'+f+'" ';a+='RoomPwd ="'+g+'" ';a+='ServerPort ="'+
e+'" ';a+='ServerIP ="'+c+'" ';a+='RealName ="'+k+'" ';a+='UserName ="'+h+'" ';a+='PersonalPictureURL ="'+m+'" ';a+='EnablePersonalPictureURL ="'+l+'" ';a+='PersonalPictureHeight ="'+u+'" ';a+='PersonalColor ="'+n+'" ';a+='Supervisor ="'+p+'" ';a+='EnableWritingBoard ="'+q+'" ';a+='EnableDrawingBoard ="'+r+'" ';a+='CanEditWritingBoard ="'+t+'" ';a+='MaxWritingBoardPages ="'+v+'" ';a+='Signature ="'+w+'" ';a+="></applet>";a+="</comment>";a+="</object>";document.write(a)}
function resize(a){if(-1==navigator.appName.indexOf("Microsoft")){var d;d=window.innerHeight-0;1200<d&&(d=1200);d=a?.9*d:.7*d;a=document.getElementById("Talx");null!=a&&(a.style.height=d+"px");window.scroll(0,0)}}
function GetPlayer(a,d){var b;b='<object classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95" id="mediaplayer1">'+('<param name="Filename" value="'+a+'">')+'<param name="AutoStart" value="True">';b+='<param name="ShowControls" value="True">';b+='<param name="ShowStatusBar" value="False">';b+='<param name="ShowDisplay" value="False">';b+='<param name="AutoRewind" value="True">';b+='<embed type="application/x-mplayer2" ';b+='pluginspage="http://microsoft.com/windows/mediaplayer/en/download/" ';b+='src="'+
a+'" ';b+='autostart="true" showcontrols="true" ';b+='id="mediaplayer1" ';b+='showstatusbar="false" showdisplay="true" autorewind="true">';b+="<noembed>"+d+"</noembed>";b+="</embed>";b+="</object>";document.write(b)}
function GetMovPlayer(a,d){var b;b='<OBJECT classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" width="320"height="255" codebase="http://www.apple.com/qtactivex/qtplugin.cab">'+('<param name="src" value="'+a+'">');b+='<param name="autoplay" value="true">';b+='<param name="controller" value="true">';b+='<param name="loop" value="true">';b+='<EMBED src="'+a+'" width="320" height="255" autoplay="true" ';b+='controller="true" loop="true" pluginspage="http://www.apple.com/quicktime/download/">';b+="<noembed>"+
d+"</noembed>";b+="</EMBED>";b+="</OBJECT>";document.write(b)}
function LoadFileUploader(a,d,b,c,e){a='<applet code="com/infomentum/appletfile/FileUpload.class" archive="FileUpload.jar" '+('codebase="/AppletFile/classesV4" width="80%" height="100" name="'+a+'" mayscript VIEWASTEXT id=applet1> ')+'<param name="cabbase" value="/AppletFile/classesV4/FileUpload.cab"> ';a+='<param name="alternateUrl" value="'+d+'">';a+='<param name="selectFolders" VALUE="true">';a+='<param name="AutoZip" VALUE="true">';a+='<param name="errorLimit" value="'+b+'">';a+='<param name="language" value="'+
c+'">';a+='<param name="noConfirm" value="true">';a+='<param name="filter1" value="All files (*.*)">';a+='<param name="filter2" value="Images (*.gif,*.jpg,*.jpeg,*.png)">';a+='<param name="directory" value="'+e+'">';a+="</applet>";document.write(a)}function TrimString(a){a=a.replace(/^\s+/g,"");return a.replace(/\s+$/g,"")}function IsPosInt(a){if(null==a)return!1;for(i=0;i<a.length;i++)if(-1=="0123456789".indexOf(a.charAt(i)))return!1;return 0<a.length}
function GetPosIntPart(a,d,b){var c;for(c=0;c<Math.min(a.length,d.length);c++)if(d[c].charAt(0).toLowerCase()==b&&IsPosInt(a[c]))return parseInt(a[c],10);return 0}function IsDateIsoFormat(a){if(null==a)return!1;a=TrimString(a);return 10==a.length&&IsPosInt(a.substr(0,4))&&"-"==a.charAt(4)&&IsPosInt(a.substr(5,2))&&"-"==a.charAt(7)&&IsPosInt(a.substr(8,2))}
function ParseDate(a,d){for(a=TrimString(a);-1!=a.search("  ");)a=a.replace("  "," ");a=a.replace(/[^0-9]/g,"-");d=d.replace(/[^yYmMdD]/g,"-");var b=a.split("-"),c=d.split("-"),e=Array(Math.min(3,b.length));e[0]=GetPosIntPart(b,c,"y");e[1]=GetPosIntPart(b,c,"m");e[2]=GetPosIntPart(b,c,"d");return e}
function IsValidDate(a,d){IsDateIsoFormat(a)&&(d="yyyy-MM-dd");var b=ParseDate(a,d);if(3!=b.length)return!1;var c=b[0],e=b[1],b=b[2];return 12<e||1>e||31<b||1>b||1900>c||2078<c||(4==e||6==e||9==e||11==e)&&30<b||2==e&&(0==c%4&&(0!=c%100||0==c%400)&&29<b||0!=c%4&&(0==c%100||0!=c%400)&&28<b)?!1:!0}
function ParseTime(a){a=a.replace(/\s/g,"");var d="",b=0,c=Array(3);c[0]=c[1]=-80;for(var e=c[2]=0;e<a.length;e++)IsPosInt(a.substr(e,1))&&(d+=a.charAt(e)),a.length-1!=e&&IsPosInt(a.substr(e,1))||(0<d.length&&3>=b&&(c[b]=parseInt(d,10)),d="",b++);a=a.toLowerCase();0<a.search("a")&&12==c[0]?c[0]-=12:0<a.search("p")&&12!=c[0]&&(c[0]+=12);a=a.replace("am","");a=a.replace("pm","");a=a.replace("a","");a=a.replace("p","");a=a.replace(/[.:0-9]/g,"");0!=a.length&&(c[0]=-80);return c}
function IsValidTime(a){var d=ParseTime(a);a=d[0];var b=d[1],d=d[2];return 0<=a&&23>=a&&0<=b&&59>=b&&0<=d&&59>=d}function OpenHelp(a,d,b){var c=top;d&&""!=d&&(c=c.frames[d]);b&&""!=b&&(c=c.frames[b]);d=800;b=600;window.width>d&&(d=window.width);window.height>b&&(b=window.height);try{return window.open(a+c.location.pathname,"","height="+b+",width="+d+",location=yes,toolbar=yes,scrollbars=yes,status=yes,menubar=yes,resizable=yes"),!1}catch(e){return!0}}
function OpenHelp2(a){var d,b;d=800;b=600;window.outerWidth&&window.outerWidth>d&&(d=window.outerWidth);window.outerHeight&&window.outerHeight>b&&(b=window.outerHeight);window.open(a,"","height="+b+",width="+d+",location=yes,toolbar=yes,scrollbars=yes,status=yes,menubar=yes,resizable=yes");return!1}function VideoPortal_PlayVideo(a,d){null!=a&&null!=a.parentNode&&raw_popup(d,"_blank","location=false,statusbar=false,menubar=false,resizable=yes,width=700,height=625")}
function setFocusToElement(a){(a=document.getElementById(a))&&a.focus();return!1}function stopEventPropagation(a){window.event?window.event.cancelBubble=!0:a.stopPropagation()}function makeDelegate(a,d,b){var c=b?function(a){c.Method.call(c.Object,a)}:function(){c.Method.call(c.Object)};c.Object=a;c.Method=d;return c}function ToggleButtonLabel(a,d,b,c){d=document.getElementById(d);a&&d&&(d.value=a.checked?b:c)}
function Hash(){this.length=0;this.items=[];for(var a=0;a<arguments.length;a+=2)"undefined"!=typeof arguments[a+1]&&(this.items[arguments[a]]=arguments[a+1],this.length++);this.removeItem=function(a){var b;"undefined"!=typeof this.items[a]&&(this.length--,b=this.items[a],delete this.items[a]);return b};this.getItem=function(a){return this.items[a]};this.setItem=function(a,b){"undefined"!=typeof b&&("undefined"==typeof this.items[a]&&this.length++,this.items[a]=b);return b};this.hasItem=function(a){return"undefined"!=
typeof this.items[a]}}function ReloadTreeMenu(a){var d=top;d&&"function"==typeof d.Reload&&d.Reload(a)}function RedirectToCourse(a){isNaN(parseInt(a,10))||window.location.replace(window.location.protocol+"//"+window.location.host+"/main.aspx?CourseId="+a)}function callInsertOrUpdatePersonSettingService(a,d,b,c){$.ajax({type:"POST",url:a,data:{settingName:b,settingValue:c},success:d()})}
function ReloadLoginLanguage(a){var d=document.location.pathname,b=document.getElementById(LoginPageSettings.userNameInputClientId);b&&b.value&&(d+="?"+LoginPageSettings.requestItems.userName+"="+escape(b.value));d+=0>d.indexOf("?")?"?":"&";d+=LoginPageSettings.requestItems.languageId+"="+a.id;document.location.replace(d)}function SetVisibiltyStyle(a,d){var b=document.getElementById(a);void 0!=b&&(b.style.visibility=d?"visible":"hidden")}
function CheckAnySelectionDoneByCheckboxName(a){a=document.getElementsByName(a);var d=!1;if(a)for(var b=0;b<a.length&&!d;++b)d=a[b].checked;return d}function HighlightNearestTd(a){$(document.getElementById(a)).closest("td").effect("highlight",{color:"#fff7bd"},1300)};
